use crate::models::Catalog;

pub fn generate_typescript_bindings() -> String {
    let bindings = r#"// Generated by `cargo run --manifest-path src-tauri/Cargo.toml --bin export_types`.
// Keep this file aligned with src-tauri/src/models.rs.

export type Locale = "en" | "zh";
export type OperatingSystem = "windows" | "macos" | "linux";
export type NetworkMode = "official" | "custom-proxy" | "china-mirror";
export type SourceKind = "official" | "package-manager" | "mirror";
export type InstallStepKind = "download" | "command" | "package-manager" | "configure";
export type ConfigAction = "append" | "set" | "write-file";

export interface LocalizedText {
  en: string;
  zh: string;
}

export interface CatalogCategory {
  id: string;
  name: LocalizedText;
  description: LocalizedText;
  icon: string;
}

export interface CatalogItem {
  id: string;
  category: string;
  name: LocalizedText;
  summary: LocalizedText;
  homepage: string;
  supportedPlatforms: OperatingSystem[];
  tags: string[];
  versions: VersionOption[];
  sources: Source[];
  detection: DetectionRule[];
  dependencies: string[];
  installSteps: InstallStepTemplate[];
  configSteps: ConfigChangeTemplate[];
}

export interface Catalog {
  schemaVersion: number;
  categories: CatalogCategory[];
  items: CatalogItem[];
}

export interface VersionOption {
  id: string;
  label: string;
  default?: boolean;
}

export interface Source {
  kind: SourceKind;
  url: string;
  notes?: LocalizedText;
}

export interface DetectionRule {
  platforms: OperatingSystem[];
  kind: string;
  program: string;
  args: string[];
  sourceHint?: string;
}

export interface InstallStepTemplate {
  id: string;
  platforms: OperatingSystem[];
  kind: InstallStepKind;
  title: LocalizedText;
  url?: string;
  mirrorUrl?: string;
  checksum?: string;
  command?: string;
  args: string[];
  source: SourceKind;
  permissions: StepPermissions;
}

export interface StepPermissions {
  requiresAdmin: boolean;
  reason?: LocalizedText;
}

export interface ConfigChangeTemplate {
  target: string;
  action: ConfigAction;
  value: string;
  backupHint: LocalizedText;
  rollback: LocalizedText;
}

export interface NetworkProfile {
  mode: NetworkMode;
  proxyUrl?: string;
  mirrorRegion?: string;
}

export interface DetectionResult {
  itemId: string;
  status: "installed" | "missing" | "unknown";
  version?: string;
  path?: string;
  source?: string;
  satisfiesRequested: boolean;
  conflicts: string[];
}

export interface PlanSelection {
  itemId: string;
  version?: string;
}

export interface PlannedStep {
  id: string;
  itemId: string;
  title: LocalizedText;
  kind: InstallStepKind;
  source: SourceKind;
  url?: string;
  checksum?: string;
  command?: string;
  args: string[];
  permissions: StepPermissions;
  configChanges: ConfigChangeTemplate[];
}
"#;

    bindings.to_string()
}

pub fn validate_generated_shape_against_catalog(_catalog: &Catalog) -> bool {
    generate_typescript_bindings().contains("export interface CatalogItem")
}
