export type {
  Catalog,
  CatalogCategory,
  CatalogItem,
  ConfigAction,
  ConfigChangeTemplate,
  DetectionResult,
  DetectionRule,
  InstallStepKind,
  InstallStepTemplate,
  Locale,
  LocalizedText,
  NetworkMode,
  NetworkProfile,
  OperatingSystem,
  PlannedStep,
  PlanSelection,
  Source,
  SourceKind,
  StepPermissions,
  VersionOption
} from "./bindings/generated";
